version: '3.8'

services:
  culling-discord-bot:
    build: .
    container_name: culling-discord-bot
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env