version: '3.8'

services:
  culling-discord-bot:
    build: .
    container_name: culling-discord-bot
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - BOT_ADMIN_USER_IDS=${BOT_ADMIN_USER_IDS}
      - BOT_ADMIN_CHANNEL_IDS=${BOT_ADMIN_CHANNEL_IDS}
      - ROLE_JOGADORES=${ROLE_JOGADORES}
      - PORT=${PORT}
      - CHANNEL_ABATE_CHAT=${CHANNEL_ABATE_CHAT}
      - CHANNEL_REGRAS=${CHANNEL_REGRAS}
      - CHANNEL_ANUNCIOS=${CHANNEL_ANUNCIOS}
      - CHANNEL_LEADERBOARD=${CHANNEL_LEADERBOARD}
      - CHANNEL_ELIMINADOS=${CHANNEL_ELIMINADOS}
      - CHANNEL_BOSSES=${CHANNEL_BOSSES}
      - CHANNEL_STAFF=${CHANNEL_STAFF}
      - CHANNEL_PEDIDOS=${CHANNEL_PEDIDOS}
      - CHANNEL_CONDICOES_VITORIA=${CHANNEL_CONDICOES_VITORIA}
      - CHANNEL_REGRAS_PENDENTES=${CHANNEL_REGRAS_PENDENTES}
      - CHANNEL_LOGS=${CHANNEL_LOGS}
      - CHANNEL_ADMIN_COMANDOS=${CHANNEL_ADMIN_COMANDOS}